-- Implantação Agro Machine

-- Limpeza inicial

DROP TABLE TBL_FIELD CASCADE CONSTRAINTS;
DROP TABLE TBL_PLOT CASCADE CONSTRAINTS;
DROP TABLE TBL_CROP CASCADE CONSTRAINTS;
DROP TABLE TBL_SENSOR CASCADE CONSTRAINTS;
DROP TABLE TBL_READING CASCADE CONSTRAINTS;

-- Criação das tabelas

-- Campos

CREATE TABLE T_FIELD (
    field_id NUMBER(3) NOT NULL,
    field_name VARCHAR(30) NOT NULL
);

ALTER TABLE T_FIELD ADD CONSTRAINT PK_FIELD PRIMARY KEY (field_id);
ALTER TABLE T_FIELD ADD CONSTRAINT UN_FIELD_NOME UNIQUE (field_name);

-- Zonas

CREATE TABLE T_PLOT (
    plot_id NUMBER(3) NOT NULL,
    field_id NUMBER(3) NOT NULL,
    plot_name VARCHAR(32) NOT NULL,
    plot_x INTEGER NOT NULL,
    plot_y INTEGER NOT NULL
);

ALTER TABLE T_PLOT ADD CONSTRAINT PK_PLOT PRIMARY KEY (plot_id);
ALTER TABLE T_PLOT ADD CONSTRAINT FK_PLOT_FIELD FOREIGN KEY (field_id) REFERENCES T_FIELD(field_id);
ALTER TABLE T_PLOT ADD CONSTRAINT UN_PLOT_NAME_FIELD UNIQUE (plot_name);

-- Cultura

CREATE TABLE T_CROP (
    crop_id NUMBER(2) NOT NULL,
    plot_id NUMBER(3) NOT NULL,
    crop_name VARCHAR(32) NOT NULL
)

ALTER TABLE T_CROP ADD CONSTRAINT PK_CROP PRIMARY KEY (crop_id);
ALTER TABLE T_CROP ADD CONSTRAINT FK_CROP_PLOT FOREIGN KEY (plot_id) REFERENCES T_PLOT(plot_id);
ALTER TABLE T_CROP ADD CONSTRAINT UN_CROP_NAME_PLOT UNIQUE (crop_name);

-- Sensor

CREATE TABLE T_SENSOR (
    sensor_id NUMBER(3) NOT NULL,
    plot_id NUMBER(3) NOT NULL,
    sensor_name VARCHAR(32) NOT NULL,
    sensor_type VARCHAR(32) NOT NULL
);

ALTER TABLE T_SENSOR ADD CONSTRAINT PK_SENSOR PRIMARY KEY (sensor_id);
ALTER TABLE T_SENSOR ADD CONSTRAINT FK_SENSOR_PLOT FOREIGN KEY (plot_id) REFERENCES T_PLOT(plot_id);
ALTER TABLE T_SENSOR ADD CONSTRAINT UN_SENSOR_NAME_PLOT UNIQUE (sensor_name);

-- Leitura

CREATE TABLE T_READING (
    reading_id NUMBER(5) NOT NULL,
    sensor_id NUMBER(3) NOT NULL,
    reading_time NUMBER(8) NOT NULL,
    reading_humidity NUMBER(3, 1)
)

time  , temperatura, umidade, bomba    , fósforo, potássio, pH
