-- Implantação Agro Machine

-- Estrutura inicial de dados

-- Limpeza inicial

DROP TABLE T_FIELDS CASCADE CONSTRAINTS;
DROP TABLE T_CROPS CASCADE CONSTRAINTS;
DROP TABLE T_PLOTS CASCADE CONSTRAINTS;
DROP TABLE T_COMPUTERS CASCADE CONSTRAINTS;
DROP TABLE T_SENSORS CASCADE CONSTRAINTS;
DROP TABLE T_READINGS CASCADE CONSTRAINTS;

-- Criação das tabelas

-- Campos

CREATE TABLE T_FIELDS (
    field_id NUMBER(3) NOT NULL,
    field_name VARCHAR(30) NOT NULL,
    field_x NUMBER(5, 1) NOT NULL,
    field_y NUMBER(5, 1) NOT NULL
);

ALTER TABLE T_FIELDS ADD CONSTRAINT PK_FIELDS PRIMARY KEY (field_id);
ALTER TABLE T_FIELDS ADD CONSTRAINT UN_FIELDS_NOME UNIQUE (field_name);
CREATE SEQUENCE seq_fields START WITH 1 INCREMENT BY 1;

-- Culturas

CREATE TABLE T_CROPS (
    crop_id NUMBER(2) NOT NULL,
    crop_name VARCHAR(32) NOT NULL
)

ALTER TABLE T_CROPS ADD CONSTRAINT PK_CROPS PRIMARY KEY (crop_id);
CREATE SEQUENCE seq_crops START WITH 1 INCREMENT BY 1;

-- Zonas

CREATE TABLE T_PLOTS (
    plot_id NUMBER(3) NOT NULL,
    field_id NUMBER(3) NOT NULL,
    crop_id NUMBER(2) NOT NULL,
    plot_name VARCHAR(32) NOT NULL,
    plot_x INTEGER NOT NULL,
    plot_y INTEGER NOT NULL
);

ALTER TABLE T_PLOTS ADD CONSTRAINT PK_PLOTS PRIMARY KEY (plot_id);
ALTER TABLE T_PLOTS ADD CONSTRAINT FK_PLOTS_FIELD FOREIGN KEY (field_id) REFERENCES T_FIELDS(field_id);
ALTER TABLE T_PLOTS ADD CONSTRAINT FK_PLOTS_CROP FOREIGN KEY (crop_id) REFERENCES T_CROPS(crop_id);
ALTER TABLE T_PLOTS ADD CONSTRAINT UN_PLOTS_NAME_FIELD UNIQUE (plot_name);
CREATE SEQUENCE seq_plots START WITH 1 INCREMENT BY 1;

-- Computadores

CREATE TABLE T_COMPUTERS (
    computer_id NUMBER(2) NOT NULL,
    plot_id NUMBER(3) NOT NULL,
    field_id NUMBER(3) NOT NULL,
    computer_name VARCHAR(32)
)

ALTER TABLE T_COMPUTERS ADD CONSTRAINT PK_COMPUTERS PRIMARY KEY (computer_id);
ALTER TABLE T_COMPUTERS ADD CONSTRAINT FK_COMPUTERS_PLOT FOREIGN KEY (plot_id) REFERENCES T_PLOTS(plot_id);
ALTER TABLE T_COMPUTERS ADD CONSTRAINT FK_COMPUTERS_FIELD FOREIGN KEY (field_id) REFERENCES T_FIELDS(field_id);
CREATE SEQUENCE seq_computers START WITH 1 INCREMENT BY 1;

-- Sensors

CREATE TABLE T_SENSORS (
    sensor_id NUMBER(3) NOT NULL,
    computer_id NUMBER(3) NOT NULL,
    sensor_name VARCHAR(32) NOT NULL,
    sensor_type VARCHAR(32) NOT NULL
)

ALTER TABLE T_SENSORS ADD CONSTRAINT PK_SENSORS PRIMARY KEY (sensor_id);
ALTER TABLE T_SENSORS ADD CONSTRAINT FK_SENSORS_COMPUTER FOREIGN KEY (computer_id) REFERENCES T_COMPUTERS(computer_id);
CREATE SEQUENCE seq_sensors START WITH 1 INCREMENT BY 1;

-- Leituras

CREATE TABLE T_READINGs (
    reading_id NUMBER(5) NOT NULL,
    computer_id NUMBER(2) NOT NULL,
    reading_time NUMBER(8) NOT NULL,
    reading_humidity_sensor NUMBER(3),
    reading_humidity_value NUMBER(4, 2),
    reading_humidity_level VARCHAR(10),
    reading_pump VARCHAR(10),
    reading_phosphorus_sensor NUMBER(3), 
    reading_phosphorus VARCHAR(10),
    reading_potassium_sensor NUMBER(3),
    reading_potassium VARCHAR(10),
    reading_ph_sensor NUMBER(3),
    reading_ph_value NUMBER(5),
    reading_ph_level VARCHAR(10),
    reading_temperature_sensor NUMBER(3),
    reading_temperature NUMBER(3, 1)
)

ALTER TABLE T_READINGS ADD CONSTRAINT PK_READINGS PRIMARY KEY (reading_id);
ALTER TABLE T_READINGS ADD CONSTRAINT FK_READINGS_COMPUTER FOREIGN KEY (computer_id) REFERENCES T_COMPUTERS(computer_id);
ALTER TABLE T_READINGS ADD CONSTRAINT FK_READINGS_HUMIDITY_SENSOR FOREIGN KEY (reading_humidity_sensor) REFERENCES T_SENSORS(sensor_id);
ALTER TABLE T_READINGS ADD CONSTRAINT FK_READINGS_PHOSPHORUS_SENSOR FOREIGN KEY (reading_phosphorus_sensor) REFERENCES T_SENSORS(sensor_id);
ALTER TABLE T_READINGS ADD CONSTRAINT FK_READINGS_POTASSIUM_SENSOR FOREIGN KEY (reading_potassium_sensor) REFERENCES T_SENSORS(sensor_id);
ALTER TABLE T_READINGS ADD CONSTRAINT FK_READINGS_PH_SENSOR FOREIGN KEY (reading_ph_sensor) REFERENCES T_SENSORS(sensor_id);
ALTER TABLE T_READINGS ADD CONSTRAINT FK_READINGS_TEMPERATURE_SENSOR FOREIGN KEY (reading_temperature_sensor) REFERENCES T_SENSORS(sensor_id);
ALTER TABLE T_READINGS ADD CONSTRAINT UN_READINGS_TIME UNIQUE (reading_time);
CREATE SEQUENCE seq_readings START WITH 1 INCREMENT BY 1;

commit;